import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Sidebar for the Physical AI & Humanoid Robotics textbook
  physicalAiHumanoidRobotics: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      items: [
        'physical-ai-humanoid-robotics/index',
        {
          type: 'category',
          label: 'Module 1: Introduction to Physical AI and Humanoid Robotics',
          items: [
            'physical-ai-humanoid-robotics/module-1-introduction/module-1-overview',
          ],
        },
        {
          type: 'category',
          label: 'Module 2: Fundamentals of Robotics',
          items: [
            'physical-ai-humanoid-robotics/module-2-robotics-fundamentals/robotics-fundamentals',
          ],
        },
        {
          type: 'category',
          label: 'Module 3: Mechanical Design of Humanoid Robots',
          items: [
            'physical-ai-humanoid-robotics/module-3-mechanical-design/mechanical-design',
          ],
        },
        {
          type: 'category',
          label: 'Module 4: Artificial Intelligence for Physical Systems',
          items: [
            'physical-ai-humanoid-robotics/module-4-ai-physical-systems/ai-physical-systems',
          ],
        },
        {
          type: 'category',
          label: 'Module 5: Perception Systems',
          items: [
            'physical-ai-humanoid-robotics/module-5-perception-systems/perception-systems',
          ],
        },
        {
          type: 'category',
          label: 'Module 6: Control Systems and Motor Planning',
          items: [
            'physical-ai-humanoid-robotics/module-6-control-systems/control-systems',
          ],
        },
        {
          type: 'category',
          label: 'Module 7: Learning in Physical Environments',
          items: [
            'physical-ai-humanoid-robotics/module-7-learning-environments/learning-environments',
          ],
        },
        {
          type: 'category',
          label: 'Module 8: Human-Robot Interaction',
          items: [
            'physical-ai-humanoid-robotics/module-8-human-robot-interaction/hri',
          ],
        },
        {
          type: 'category',
          label: 'Module 9: Applications and Use Cases',
          items: [
            'physical-ai-humanoid-robotics/module-9-applications/applications',
          ],
        },
        {
          type: 'category',
          label: 'Module 10: Simulation, Development, and Deployment',
          items: [
            'physical-ai-humanoid-robotics/module-10-simulation-deployment/simulation-deployment',
          ],
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
